### ISSUE TITLE
Unify still and master branches

### ISSUE THREAD

**Issue by mvz** [cucumber/aruba#598]
## Summary

We should update the `still` development branch so the change to `master` is no more than a removal of deprecations.

## Details

This will be a combination of backporting bug fixes, moving deprecated code, moving other files. The end goal is that merging `still` into `master` will only lead to conflicts in deleted files that contain the code deprecated in the `0.14.x` line and removed in `1.0.0`.

## Motivation and Context

A lot of projects that use Aruba are not even on `0.14.x` yet. We should be able to tell them that they should do that and fix all deprecations, and then they should be able to safely move to upcoming `1.0.0`. Since there are still reasons why projects are stuck on pre-0.14 versions, these reasons should be taken away first. This means Aruba development is stuk on 0.14 for a while longer as well. To avoid duplicate effort, `still` and `master` need to be made as similar as possible.

We may have to revert some breaking behavioral changes between still and master eventually, as well as some deprecations.

## Relevant parts and their pull requests

This list will be updated with new pull requests when they become available.

* [x] Main work (will be split into smaller pull requests): #571
* [x] Deprecate `#use_clean_gemset`: #597
* [x] Re-organize feature files: #602
* [x] Re-organize spec files: #603
* [x] Update changelog format: #599
* [x] Backport ability to use decimal timeout values: #621.
* [x] Backport switch to `aruba-test-cli`: #620
* [x] Move deprecated cucumber steps into a separate file: #622.
* [ ] Backport Windows-related fixes to 0.14.x
* [x] Forward-port JRuby fix: #635.
* [ ] Update master branch with some changes from still?
* [x] Roll back breaking changes in master: #644.

**Comment by luke-hill** [comment]
If you need any help with this let me know.

I guess this is just a case of get all of the bug fixes that were only released into 0.14 into the 1.0 version then release 1.0? Or are we planning on releasing a 0.14.10 0.14.11 e.t.c.?

**Comment by mvz** [comment]
It's a little more complicated since 1.0 has some breaking changes and drops support for older Rubies, which is a particular problem for, e.g., rspec.

So, there may be some more point releases for 0.14.

**Comment by luke-hill** [comment]
Question... 

Should we at some point do a set of staged updates to the dependencies on `still` ??

Things I thought about.

1) Cucumber dependency - Remove v1 (So 2.0 and above), then Remove v2 (So 3.0 and above)
2) Update Rubies - Remove all 1.x series (So 2.0 and above), then remove 2.1/2.2 (So 2.3 and above)
3) Update Rubocop - Probably could do a bump to the 0.50 range (As this will inevitably require a bunch of auto-fixes), and then another bump to 0.69 (We should also lock it down to a patch version, as the updates from one minor to another are usually quite big.
4) Remove rspec 2.x capabilities (This should be quite easy)

I'm happy to raise some PR's for these if you are happy to merge them into the next 0.14 release?

**Comment by mvz** [comment]
I have a feeling 1.0 is nearly ready. I'm probably not going to fully unify master and still to the point of being able to merge still into master.

That being the case, I'm not planning to drop compatibilities with Ruby etc. in the 0.14.x series. So, my current vague plan is to release a final 1.0.0 pre-release soonish and accompany that with some publicity to get people to try to upgrade via latest 0.14.x. Then, we can fix any bugs coming from that and release 1.0.0.

**Comment by luke-hill** [comment]
Where are we at with this?

I'm aware we aren't going to drop the `0.14` series any time soon, but can we release an official 1.0 cut. Just so we can at least gather some feedback from users. We can always release future patch releases if needs be.

Also do we know our major inhibitors for moving off `0.14`. From our last conversation some people are stuck on a `0.8.x` series right? Do we know who they are / what needs fixing for them? I know rspec are now on a later version of aruba.

**Comment by mvz** [comment]
I discovered one more bug for the `0.14.x` series :disappointed:.

**Comment by mvz** [comment]
>  can we release an official 1.0 cut.

Yes, I think it's time. The bug in 0.14.x has to do with Bundler not picking up the right Gemfile when trying to run it with a clean environment. This is a bit of an edge case and has a workaround.

**Comment by mvz** [comment]
This is done as far as it will be done.
